apiVersion: v1
kind: Secret
metadata:
  name: mathwizz-secrets
  namespace: mathwizz
type: Opaque
data:
  DB_PASSWORD: bWF0aHdpenpfZGV2XzE3Njc3Mjc3NjU=
  POSTGRES_PASSWORD: bWF0aHdpenpfZGV2XzE3Njc3Mjc3NjU=
  JWT_SECRET: and0X3NlY3JldF8wY2QwMGM4ZTMxNjVlNGMxZDQzNjRlZTliOTQxODk0NmNmZjIxMWM5YzIxNWVjYjdkN2E4ZDE4OTBlZWFiNGMw
